### ISSUE TITLE
No link to github on page

### ISSUE THREAD

**Issue by bennovack** [hack4impact/gpcah#78]
A github link goes a long way toward helping new developers get on board - show them the site as it exists, and within a couple of clicks they're looking at the issues they can dive into.

**Comment by sandlerben** [comment]
Thanks for making this issue. What do you mean by "on page"? Do you mean on
the actual site <http://phillyfoodfinder.org/>?

**Comment by bennovack** [comment]
Exactly. I was looking at the site while on the phone with the Office of Sustainability to see if Code for Philly could help out with some future dev work, and it wasn't obvious whether it was open source at all or where to find code. For a moment I was afraid the source might not even be available!

**Comment by nancywong** [comment]
Oh cool, that's a good idea. @sandlerben we can add a line in the footer e.g. "Developed by Hack4Impact in partnership with the Philadelphia Food Policy Advisory Council and the Greater Philadelphia Coalition Against Hunger. Interested in contributing? Check out our [project page]<github link>."

**Comment by sandlerben** [comment]
See #79
