### ISSUE TITLE
New site submissions

### ISSUE THREAD

**Issue by phillyfpac** [hack4impact/gpcah#80]
phillyfoodfinder.org has a form where food resource site managers can submit their food resource to become a new pin on the map -- http://www.phillyfoodfinder.org/propose-resource 

On the admin side, we have received two submissions but are unable to open the submissions to see the site details and approve or reject the site. 

Any insight or help on this is greatly appreciated!

**Comment by sandlerben** [comment]
@phillyfpac That's a strange bug. I'm going to look into it.

**Comment by sandlerben** [comment]
Can you email me at ben1sandler(at)gmail.com?

**Comment by sandlerben** [comment]
The bug has to do with resources proposed by people with periods in their names. Very strange!

**Comment by sandlerben** [comment]
I have fixed the problem and will push an update shortly.

**Comment by sandlerben** [comment]
http://stackoverflow.com/questions/350292/how-do-i-get-jquery-to-select-elements-with-a-period-in-their-id

**Comment by phillyfpac** [comment]
Thanks Ben!! This is awesome. Let us know if there's anything we need to do on our end.

**Comment by sandlerben** [comment]
@phillyfpac Should be working now

Fixed in #82 and #83

**Comment by phillyfpac** [comment]
Yes it does! Thank you Ben!
