### ISSUE TITLE
Notification from Heroku Hosting

### ISSUE THREAD

**Issue by phillyfpac** [hack4impact/gpcah#86]
FPAC received the following email from Heroku a couple weeks ago, and we have no idea what it means. Any insight appreciated!

---

From: Heroku Notifications <bot@heroku.com>
Date: Mon, Feb 22, 2016 at 6:46 AM
Subject: Your database requires maintenance.
To: phillyfoodinfo@gmail.com
 
Your database (REDIS on gpcah) is currently suffering from a critical hardware issue that may soon take the database offline. This is likely due to an underlying hardware issue and not something caused by your application.

We are preparing a replacement database, on a new host, which we will then use to replace the problematic one.

If you've copied the value of REDIS_URL to any other apps or tools (such as database administration tools), you'll need to update those values.

**Comment by sandlerben** [comment]
@phillyfpac I also received that email. This shouldn't be a problem because the application only uses redis as a non-persistent cache. In other words, nothing that needs to be stored permanently is stored in redis.
