### ISSUE TITLE
Address search box not working

### ISSUE THREAD

**Issue by phillyfpac** [hack4impact/gpcah#88]
A user brought this issue to our attention today. When you enter a zip code or address into the search box and hit search, an error pops up that says -  "www.Phillyfoodfinder.org says : Cannot find [zip code or address]."

It does not matter what you enter into the search box, the same error occurs. Changing internet applications also does not resolve the bug. 

Please help!

Screenshot of the error message:

![pff bug 6 7 16](https://cloud.githubusercontent.com/assets/16429508/15872165/16ae2fcc-2cc6-11e6-80ba-cf1a52855955.jpg)

**Comment by sandlerben** [comment]
This happened because phillyfoodfinder exceeded the daily limits of the
Google's geocoding API. I signed up for a (free) API key and added it to
the production server. This issue should now be fixed.

**Comment by phillyfpac** [comment]
Thanks so much Ben, it's working fine!
